name: GamemodePvP
main: ml.gamemodepvp.CoreMain
version: 0.2
description: SuperSized GamemodePVP Plugin designed to Replicate a Cod style Gaming.
author: bfox1
depend: [ScalaLoader, XStreamLoader]

commands:
  class:
    description: A Class selection Gui
    permission: gamemodepvp.class
    aliases: [c]
  createNewArena:
    description: Creates new ArenaVoid world
    permission: gamemodepvp.world.createworld
  teleporttoworld:
    description: teleport to world destination
    permission: gamemodepvp.world.teleportworld
  deleteworld:
    description: deletes world
    permission: gamemodepvp.world.delworld

  getregionlist:
    description: Returns List of Regions for world.
    permission: gamemodepvp.world.getregion
  setmapsize:
    description: Sets Arena Map Size
    permission: gamemodepvp.world.mapsize
  removeMapRegion:
    description: Removes Region Specified
    permission: gamemodepvp.world.removemapsize
  setupregion:
    description: Sets Region Building Mode on.
    permission: gamemodepvp.world.setupregion
  createregion:
    description: Creates the Region defined
    permission: gamemodepvp.world.createregion
  removeregion:
    description: Removes the defined region/
    permission: gamemodepvp.world.removeregion

  setregionflag:
    description: Sets special flags for the region.
    permission: GamemodePvP.world.setregionflag
    default: false

  setplayerflag:
    description: Sets special flags for player in specific region
    permission: gamemodepvp.world.setplayerflag

  ecomoney:
    description: MONEY
    permission: GamemodePvP.ecomoney.money
    aliases: [c]
    default: true
  savedata:
    description: Saves player data.
    permission: gamemodepvp.savedata
  loaddata:
    description: Saves player data.
    permission: gamemodepvp.loaddata
  register:
    description: Registers your account throught the GamemodePVP Network!
    permission: gamemodepvp.register
    Usage: Hmm. Try /register <email> <password>?

  setplayerrank:
    description: Sets Players Rank.
    permission: gamemodepvp.rank.setrank
    usage: /setPlayerRank <name> <rankName>
  removeplayerrank:
    description: Removes players rank
    permission: gamemodepvp.rank.removerank
    usage: /removePlayerRank <name>

permissions:
  gamemodepvp.*:
    description: Gives access to all GamemodePVP Permissions
    children:
      gamemodepvp.class: true
      gamemodepvp.world.createworld: true
      gamemodepvp.world.teleportworld: true
      gamemodepvp.world.getregion: true
      gamemodepvp.world.mapsize: true
      gamemodepvp.world.removemapsize: true
      gamemodepvp.world.setupregion: true
      gamemodepvp.world.createregion: true
      gamemodepvp.world.setregionflag: true
      gamemodepvp.world.setplayerflag: true
      gamemodepvp.ecomoney.money: true

    GamemodePvP.ecomoney.money:
    description: check Money and pay players
    default: true

    gamemodepvp.world.setregionflag:
    description: Sets Region flag
    default: op